sudo: false
language: java
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt: 
    packages:
      - firefox
      - firefox-geckodriver
before_script:
  - psql -c 'create database apptest;' -U postgres
script: boot test
install:
  - mkdir -p ~/bin
  - export PATH=~/bin:$PATH
  # Could use `latest` tag instead of version number
  - curl -L https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh -o ~/bin/boot
  - chmod +x ~/bin/boot
  # - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
env:
  matrix:
    - BOOT_CLOJURE_VERSION=1.10.3
jdk:
  - openjdk11
cache:
  directories:
  - $HOME/.m2
  - $HOME/.boot/cache/bin
  - $HOME/.boot/cache/lib
  - $HOME/bin
